import { ElevatorDetails } from '../models/elevatorDetailModel';

export const elevatorsDetails: ElevatorDetails[] = [
  {
    id: 1,
    address: 'Václavské náměstí 12, Praha 1',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-10',
    status: 'Aktivní',
    installationDate: '2020-06-15',
    manufacturer: 'Otis',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 8,
    maintenanceCompany: 'LiftServis Praha s.r.o.',
    maintenanceContactName: 'Jan Novák',
    maintenanceContactPhone: '+420 777 123 456',
    maintenanceContactEmail: 'servis@liftservis.cz',
    notes:
      'Výtah je v dobrém stavu, bez závad. Další servis naplánován na říjen 2025.',
  },
  {
    id: 2,
    address: 'Karla IV. 8, Hradec Králové',
    type: 'Nákladní',
    model: 'Schindler 5500',
    lastService: '2025-03-12',
    status: 'Mimo provoz',
    installationDate: '2020-08-01',
    manufacturer: 'Schindler',
    capacityKg: 1600,
    maxPersons: 21,
    numberOfStops: 10,
    maintenanceCompany: 'LiftServis Hradec s.r.o.',
    maintenanceContactName: 'Petr Svoboda',
    maintenanceContactPhone: '+420 777 234 567',
    maintenanceContactEmail: 'hradec@liftservis.cz',
    notes: 'Výtah mimo provoz kvůli poruše motoru. Oprava probíhá.',
  },
  {
    id: 3,
    address: 'Náměstí Svobody 5, Brno',
    type: 'Osobní',
    model: 'KONE EcoSpace',
    lastService: '2025-05-02',
    status: 'Plánovaný servis',
    installationDate: '2019-11-10',
    manufacturer: 'KONE',
    capacityKg: 800,
    maxPersons: 10,
    numberOfStops: 6,
    maintenanceCompany: 'KONE Servis Brno',
    maintenanceContactName: 'Tomáš Dvořák',
    maintenanceContactPhone: '+420 777 345 678',
    maintenanceContactEmail: 'brno@koneservis.cz',
    notes: 'Servis naplánován na červen 2025. Výtah je dočasně odstaven.',
  },
  {
    id: 4,
    address: 'Sokolovská 99, Praha 8',
    type: 'Evakuační',
    model: 'ThyssenKrupp Synergy',
    lastService: '2025-02-28',
    status: 'Aktivní',
    installationDate: '2021-01-05',
    manufacturer: 'ThyssenKrupp',
    capacityKg: 1200,
    maxPersons: 16,
    numberOfStops: 9,
    maintenanceCompany: 'TK Elevator Praha',
    maintenanceContactName: 'Martin Černý',
    maintenanceContactPhone: '+420 777 456 789',
    maintenanceContactEmail: 'praha@tkelevator.cz',
    notes: 'Evakuační výtah pravidelně testován. V pořádku.',
  },
  {
    id: 5,
    address: 'U Stadionu 3, Ostrava',
    type: 'Nákladní',
    model: 'Otis Gen2',
    lastService: '2025-03-20',
    status: 'Mimo provoz',
    installationDate: '2018-07-23',
    manufacturer: 'Otis',
    capacityKg: 2000,
    maxPersons: 0,
    numberOfStops: 5,
    maintenanceCompany: 'Otis Ostrava',
    maintenanceContactName: 'Lukáš Procházka',
    maintenanceContactPhone: '+420 777 567 890',
    maintenanceContactEmail: 'ostrava@otis.cz',
    notes: 'Výtah porouchaný. Očekává se výměna součástek.',
  },
  {
    id: 6,
    address: 'Husova 20, Plzeň',
    type: 'Osobní',
    model: 'Schindler 3300',
    lastService: '2025-04-15',
    status: 'Aktivní',
    installationDate: '2021-04-30',
    manufacturer: 'Schindler',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 7,
    maintenanceCompany: 'Schindler CZ',
    maintenanceContactName: 'Jakub Horák',
    maintenanceContactPhone: '+420 777 678 901',
    maintenanceContactEmail: 'plzen@schindler.cz',
    notes: 'Výtah prošel bezproblémovým servisem.',
  },
  {
    id: 7,
    address: 'Lidická 31, Brno',
    type: 'Osobní',
    model: 'KONE MonoSpace',
    lastService: '2025-05-05',
    status: 'Aktivní',
    installationDate: '2020-09-18',
    manufacturer: 'KONE',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 6,
    maintenanceCompany: 'KONE Servis Brno',
    maintenanceContactName: 'Michal Král',
    maintenanceContactPhone: '+420 777 789 012',
    maintenanceContactEmail: 'servis@kone.cz',
    notes: 'Výtah je v bezvadném stavu.',
  },
  {
    id: 8,
    address: 'Pekařská 55, Brno',
    type: 'Nákladní',
    model: 'ThyssenKrupp Evolution',
    lastService: '2025-01-19',
    status: 'Plánovaný servis',
    installationDate: '2017-05-10',
    manufacturer: 'ThyssenKrupp',
    capacityKg: 2500,
    maxPersons: 0,
    numberOfStops: 4,
    maintenanceCompany: 'TK Elevator CZ',
    maintenanceContactName: 'David Beneš',
    maintenanceContactPhone: '+420 777 890 123',
    maintenanceContactEmail: 'brno@tke.cz',
    notes: 'Servis naplánován na květen 2025.',
  },
  {
    id: 9,
    address: 'Jungmannova 10, Praha 1',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-01',
    status: 'Aktivní',
    installationDate: '2022-02-11',
    manufacturer: 'Otis',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 7,
    maintenanceCompany: 'Otis Praha',
    maintenanceContactName: 'Václav Fiala',
    maintenanceContactPhone: '+420 777 901 234',
    maintenanceContactEmail: 'praha1@otis.cz',
    notes: 'Bez závad. Výtah používán denně.',
  },
  {
    id: 10,
    address: 'Zelená 7, Olomouc',
    type: 'Osobní',
    model: 'KONE EcoDisc',
    lastService: '2025-03-25',
    status: 'Mimo provoz',
    installationDate: '2016-09-09',
    manufacturer: 'KONE',
    capacityKg: 630,
    maxPersons: 8,
    numberOfStops: 5,
    maintenanceCompany: 'KONE Morava',
    maintenanceContactName: 'Radek Sedláček',
    maintenanceContactPhone: '+420 777 012 345',
    maintenanceContactEmail: 'olomouc@kone.cz',
    notes: 'Závada na dveřích. Čeká na opravu.',
  },
  {
    id: 11,
    address: 'Komenského 2, Jihlava',
    type: 'Osobní',
    model: 'ThyssenKrupp Synergy',
    lastService: '2025-03-15',

    status: 'Aktivní',
    installationDate: '2020-01-20',
    manufacturer: 'ThyssenKrupp',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 6,
    maintenanceCompany: 'TK Elevator Jihlava',
    maintenanceContactName: 'Ondřej Němec',
    maintenanceContactPhone: '+420 777 111 222',
    maintenanceContactEmail: 'jihlava@tkelevator.cz',
    notes: 'Pravidelný servis proveden bez problémů.',
  },
  {
    id: 12,
    address: 'Masarykova 88, Ústí nad Labem',
    type: 'Nákladní',
    model: 'Schindler 5500',
    lastService: '2025-05-01',

    status: 'Aktivní',
    installationDate: '2022-07-14',
    manufacturer: 'Schindler',
    capacityKg: 1800,
    maxPersons: 0,
    numberOfStops: 8,
    maintenanceCompany: 'Schindler CZ',
    maintenanceContactName: 'Filip Mareš',
    maintenanceContactPhone: '+420 777 222 333',
    maintenanceContactEmail: 'usti@schindler.cz',
    notes: 'Výtah připraven pro intenzivní provoz.',
  },
  {
    id: 13,
    address: 'Dvořákova 15, Liberec',
    type: 'Schodišťová plošina',
    model: 'Stannah Siena',
    lastService: '2025-02-10',

    status: 'Plánovaný servis',
    installationDate: '2019-06-05',
    manufacturer: 'Stannah',
    capacityKg: 250,
    maxPersons: 1,
    numberOfStops: 2,
    maintenanceCompany: 'Stannah CZ',
    maintenanceContactName: 'Roman Kolář',
    maintenanceContactPhone: '+420 777 333 444',
    maintenanceContactEmail: 'liberec@stannah.cz',
    notes: 'Plošina bude servisována v červenci 2025.',
  },
  {
    id: 14,
    address: 'Česká 25, Brno',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-12',

    status: 'Aktivní',
    installationDate: '2021-03-03',
    manufacturer: 'Otis',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 5,
    maintenanceCompany: 'Otis Brno',
    maintenanceContactName: 'Daniel Růžička',
    maintenanceContactPhone: '+420 777 444 555',
    maintenanceContactEmail: 'brno@otis.cz',
    notes: 'Výtah pravidelně kontrolován, vše v pořádku.',
  },
  {
    id: 15,
    address: 'Třída Míru 45, Pardubice',
    type: 'Evakuační',
    model: 'KONE TransitMaster',
    lastService: '2025-03-22',

    status: 'Aktivní',
    installationDate: '2020-12-15',
    manufacturer: 'KONE',
    capacityKg: 1300,
    maxPersons: 15,
    numberOfStops: 7,
    maintenanceCompany: 'KONE CZ',
    maintenanceContactName: 'Adam Urban',
    maintenanceContactPhone: '+420 777 555 666',
    maintenanceContactEmail: 'pardubice@kone.cz',
    notes: 'Evakuační výtah je ve výborném technickém stavu.',
  },
  {
    id: 16,
    address: 'Resslova 10, Praha 2',
    type: 'Osobní',
    model: 'Schindler 3300',
    lastService: '2025-02-27',

    status: 'Mimo provoz',
    installationDate: '2017-10-10',
    manufacturer: 'Schindler',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 6,
    maintenanceCompany: 'Schindler Praha',
    maintenanceContactName: 'Jaroslav Kříž',
    maintenanceContactPhone: '+420 777 666 777',
    maintenanceContactEmail: 'praha2@schindler.cz',
    notes: 'Výtah mimo provoz kvůli výměně hlavního řídicího systému.',
  },
  {
    id: 17,
    address: 'Hlavní 1, Zlín',
    type: 'Nákladní',
    model: 'Otis SkyRise',
    lastService: '2025-04-30',

    status: 'Aktivní',
    installationDate: '2021-06-25',
    manufacturer: 'Otis',
    capacityKg: 3000,
    maxPersons: 0,
    numberOfStops: 12,
    maintenanceCompany: 'Otis Zlín',
    maintenanceContactName: 'Matěj Malý',
    maintenanceContactPhone: '+420 777 777 888',
    maintenanceContactEmail: 'zlin@otis.cz',
    notes: 'Nákladní výtah po servisu bez připomínek.',
  },
  {
    id: 18,
    address: 'Studentská 12, Plzeň',
    type: 'Osobní',
    model: 'KONE MonoSpace',
    lastService: '2025-04-05',

    status: 'Plánovaný servis',
    installationDate: '2019-08-30',
    manufacturer: 'KONE',
    capacityKg: 800,
    maxPersons: 10,
    numberOfStops: 6,
    maintenanceCompany: 'KONE Plzeň',
    maintenanceContactName: 'Štěpán Jelínek',
    maintenanceContactPhone: '+420 777 888 999',
    maintenanceContactEmail: 'plzen@kone.cz',
    notes: 'Servis naplánován na červenec 2025.',
  },
  {
    id: 19,
    address: 'Na Příkopě 15, Praha 1',
    type: 'Osobní',
    model: 'ThyssenKrupp Evolution',
    lastService: '2025-05-01',

    status: 'Aktivní',
    installationDate: '2022-03-01',
    manufacturer: 'ThyssenKrupp',
    capacityKg: 1000,
    maxPersons: 13,
    numberOfStops: 5,
    maintenanceCompany: 'TK Elevator CZ',
    maintenanceContactName: 'Dominik Pokorný',
    maintenanceContactPhone: '+420 777 999 000',
    maintenanceContactEmail: 'naprikope@tke.cz',
    notes: 'Výtah zkontrolován a uveden do provozu.',
  },
  {
    id: 20,
    address: 'Horní 23, Opava',
    type: 'Schodišťová plošina',
    model: 'Acorn 180',
    lastService: '2025-03-10',

    status: 'Mimo provoz',
    installationDate: '2018-11-12',
    manufacturer: 'Acorn',
    capacityKg: 200,
    maxPersons: 1,
    numberOfStops: 2,
    maintenanceCompany: 'Acorn CZ',
    maintenanceContactName: 'Ladislav Holub',
    maintenanceContactPhone: '+420 777 000 111',
    maintenanceContactEmail: 'opava@acorn.cz',
    notes: 'Plošina mimo provoz – čeká na náhradní díly.',
  },
];
