import { ElevatorListItem } from '../models/elevatorListItem';

export const elevatorList: ElevatorListItem[] = [
  {
    id: 1,
    address: 'Václavské náměstí 12, Praha 1',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-10',
    maintenance: 'Jan Novák',
    status: 'Aktivní',
  },
  {
    id: 2,
    address: 'Karla IV. 8, Hradec Králové',
    type: 'Nákladní',
    model: 'Schindler 5500',
    lastService: '2025-03-12',
    maintenance: 'Petr Svoboda',
    status: 'Mimo provoz',
  },
  {
    id: 3,
    address: 'Náměstí Svobody 5, Brno',
    type: 'Osobní',
    model: 'KONE EcoSpace',
    lastService: '2025-05-02',
    maintenance: 'Tomáš Dvořák',
    status: 'Plánovaný servis',
  },
  {
    id: 4,
    address: 'Sokolovská 99, Praha 8',
    type: 'Evakuační',
    model: 'ThyssenKrupp Synergy',
    lastService: '2025-02-28',
    maintenance: 'Martin Černý',
    status: 'Aktivní',
  },
  {
    id: 5,
    address: 'U Stadionu 3, Ostrava',
    type: 'Nákladní',
    model: 'Otis Gen2',
    lastService: '2025-03-20',
    maintenance: 'Lukáš Procházka',
    status: 'Mimo provoz',
  },
  {
    id: 6,
    address: 'Husova 20, Plzeň',
    type: 'Osobní',
    model: 'Schindler 3300',
    lastService: '2025-04-15',
    maintenance: 'Jakub Horák',
    status: 'Aktivní',
  },
  {
    id: 7,
    address: 'Lidická 31, Brno',
    type: 'Osobní',
    model: 'KONE MonoSpace',
    lastService: '2025-05-05',
    maintenance: 'Michal Král',
    status: 'Aktivní',
  },
  {
    id: 8,
    address: 'Pekařská 55, Brno',
    type: 'Nákladní',
    model: 'ThyssenKrupp Evolution',
    lastService: '2025-01-19',
    maintenance: 'David Beneš',
    status: 'Plánovaný servis',
  },
  {
    id: 9,
    address: 'Jungmannova 10, Praha 1',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-01',
    maintenance: 'Václav Fiala',
    status: 'Aktivní',
  },
  {
    id: 10,
    address: 'Zelená 7, Olomouc',
    type: 'Osobní',
    model: 'KONE EcoDisc',
    lastService: '2025-03-25',
    maintenance: 'Radek Sedláček',
    status: 'Mimo provoz',
  },
  {
    id: 11,
    address: 'Komenského 2, Jihlava',
    type: 'Osobní',
    model: 'ThyssenKrupp Synergy',
    lastService: '2025-03-15',
    maintenance: 'Ondřej Němec',
    status: 'Aktivní',
  },
  {
    id: 12,
    address: 'Masarykova 88, Ústí nad Labem',
    type: 'Nákladní',
    model: 'Schindler 5500',
    lastService: '2025-05-01',
    maintenance: 'Filip Mareš',
    status: 'Aktivní',
  },
  {
    id: 13,
    address: 'Dvořákova 15, Liberec',
    type: 'Schodišťová plošina',
    model: 'Stannah Siena',
    lastService: '2025-02-10',
    maintenance: 'Roman Kolář',
    status: 'Plánovaný servis',
  },
  {
    id: 14,
    address: 'Česká 25, Brno',
    type: 'Osobní',
    model: 'Otis Gen2',
    lastService: '2025-04-12',
    maintenance: 'Daniel Růžička',
    status: 'Aktivní',
  },
  {
    id: 15,
    address: 'Třída Míru 45, Pardubice',
    type: 'Evakuační',
    model: 'KONE TransitMaster',
    lastService: '2025-03-22',
    maintenance: 'Adam Urban',
    status: 'Aktivní',
  },
  {
    id: 16,
    address: 'Resslova 10, Praha 2',
    type: 'Osobní',
    model: 'Schindler 3300',
    lastService: '2025-02-27',
    maintenance: 'Jaroslav Kříž',
    status: 'Mimo provoz',
  },
  {
    id: 17,
    address: 'Hlavní 1, Zlín',
    type: 'Nákladní',
    model: 'Otis SkyRise',
    lastService: '2025-04-30',
    maintenance: 'Matěj Malý',
    status: 'Aktivní',
  },
  {
    id: 18,
    address: 'Studentská 12, Plzeň',
    type: 'Osobní',
    model: 'KONE MonoSpace',
    lastService: '2025-04-05',
    maintenance: 'Štěpán Jelínek',
    status: 'Plánovaný servis',
  },
  {
    id: 19,
    address: 'Na Příkopě 15, Praha 1',
    type: 'Osobní',
    model: 'ThyssenKrupp Evolution',
    lastService: '2025-05-01',
    maintenance: 'Dominik Pokorný',
    status: 'Aktivní',
  },
  {
    id: 20,
    address: 'Horní 23, Opava',
    type: 'Schodišťová plošina',
    model: 'Acorn 180',
    lastService: '2025-03-10',
    maintenance: 'Ladislav Holub',
    status: 'Mimo provoz',
  },
];
